export interface Wallpaper {
  url: string;
  name: string;
}
export interface WallpaperWithDetails extends Wallpaper {
  width: number;
  height: number;
  device: string;
  liked: boolean;
  suggested: boolean;
  library: boolean;
}
const wallpapers: WallpaperWithDetails[] = [
  {
    name: "Neon Dreams",
    url: "https://picsum.photos/id/25/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Golden Beach",
    url: "https://picsum.photos/id/12/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: true,
    suggested: false,
    library: true,
  },
  {
    name: "Mountain Valley",
    url: "https://picsum.photos/id/11/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Purple Sky",
    url: "https://picsum.photos/id/26/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Forest River",
    url: "https://picsum.photos/id/10/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Retro Sunset",
    url: "https://picsum.photos/id/35/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: true,
    library: false,
  },
  {
    name: "Pink Horizon",
    url: "https://picsum.photos/id/36/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Silent Forest",
    url: "https://picsum.photos/id/13/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Blue Ocean",
    url: "https://picsum.photos/id/14/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Night Forest",
    url: "https://picsum.photos/id/32/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Dark Amoled",
    url: "https://picsum.photos/id/27/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Autumn Road",
    url: "https://picsum.photos/id/16/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Snow Peaks",
    url: "https://picsum.photos/id/15/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Night Sky",
    url: "https://picsum.photos/id/17/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Minimal Waves",
    url: "https://picsum.photos/id/28/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "City Lights",
    url: "https://picsum.photos/id/29/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: true,
    suggested: false,
    library: false,
  },
  {
    name: "Blue Gradient",
    url: "https://picsum.photos/id/30/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Space Journey",
    url: "https://picsum.photos/id/31/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Desert Dunes",
    url: "https://picsum.photos/id/18/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Crystal Lake",
    url: "https://picsum.photos/id/19/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: true,
    library: false,
  },
  {
    name: "Green Hills",
    url: "https://picsum.photos/id/20/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Sunset Glow",
    url: "https://picsum.photos/id/21/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Ocean Breeze",
    url: "https://picsum.photos/id/33/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Golden Clouds",
    url: "https://picsum.photos/id/34/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: true,
    library: true,
  },
  {
    name: "Galaxy View",
    url: "https://picsum.photos/id/24/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: false,
  },
  {
    name: "Rocky Coast",
    url: "https://picsum.photos/id/22/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Deep Canyon",
    url: "https://picsum.photos/id/23/3840/2160",
    width: 3840,
    height: 2160,
    device: "desktop",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Abstract Flow",
    url: "https://picsum.photos/id/37/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Moonlight",
    url: "https://picsum.photos/id/38/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Moonlight",
    url: "https://picsum.photos/id/41/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: true,
  },
  {
    name: "Emerald Forest",
    url: "https://picsum.photos/id/39/1440/3200",
    width: 1440,
    height: 3200,
    device: "mobile",
    liked: false,
    suggested: false,
    library: true,
  },
];

export default function useWallpaper() {
  return wallpapers;
}

export function useLikedWallpaper () {
  return wallpapers.filter((wallpaper)=> wallpaper.liked)
}

export function useSuggestedallpaper () {
  return wallpapers.filter((wallpaper)=> wallpaper.suggested)
}

export function useLibraryWallpaper () {
  return wallpapers.filter((wallpaper)=> wallpaper.library)
}
